import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import CoverSection from '../components/CoverSection'
import HowItWorks from '../components/HowItWorks'
import { useState } from 'react'

const Home: NextPage = () => {
  const [loggedIn, setLoggedIn] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Amicopy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header loggedIn={loggedIn} />

        <CoverSection loggedIn={loggedIn} /> 
        <a id="howItWorks"></a>       
        <div style={{minHeight: '4rem'}}></div>

        <HowItWorks />
        <div style={{minHeight: '4rem'}}></div>
        
      </main>
      <br/><br/>
      <br/><br/>
      <br/><br/>
      <br/><br/>
      <br/><br/>
      <br/><br/>
      <br/>
    </div>
  )
}

export default Home
