# Generated by Django 3.2.12 on 2022-03-13 03:39

import django.core.validators
from django.db import migrations, models
import transactions.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='files_archive',
            field=models.FileField(upload_to=transactions.models.models.shared_files_upload_path, validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
