# Generated by Django 3.2.12 on 2022-03-13 04:52

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220313_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=12, prefix='', verbose_name='session code'),
        ),
        migrations.AddConstraint(
            model_name='sessiondelete',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_session_delete'),
        ),
        migrations.AddConstraint(
            model_name='sessiondevices',
            constraint=models.UniqueConstraint(fields=('session', 'device'), name='unique_session_with_device'),
        ),
        migrations.AddConstraint(
            model_name='transactiondelete',
            constraint=models.UniqueConstraint(fields=('transaction', 'user'), name='unique_transaction_delete'),
        ),
        migrations.AddConstraint(
            model_name='transactiontodevices',
            constraint=models.UniqueConstraint(fields=('transaction', 'device'), name='unique_transaction_device'),
        ),
    ]
