# Generated by Django 3.2.12 on 2022-03-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20220313_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondevices',
            name='device',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.RESTRICT, related_name='session_devices', related_query_name='session_device', to='transactions.device'),
        ),
    ]
