# Generated by Django 3.2.12 on 2022-03-13 20:47

import django.core.validators
from django.db import migrations, models
import transactions.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_sessiondevices_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='files_archive',
            field=models.FileField(blank=True, upload_to=transactions.models.models.shared_files_upload_path, validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('browser_session_id', ''), _negated=True), ('user__isnull', True)), name='browser_session_id_and_user_id_not_both_unset'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_content', ''), _negated=True), models.Q(('files_archive', ''), _negated=True)), name='text_and_file_not_both_empty'),
        ),
    ]
