# Generated by Django 3.2.12 on 2022-03-15 23:32

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20220313_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=core.fields.ReadableShortUUIDField(alphabet=None, length=12, max_length=20, prefix='', verbose_name='session code'),
        ),
    ]
