# Generated by Django 3.2.12 on 2022-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20220327_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='num_transactions',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
