# Generated by Django 3.2.12 on 2022-04-02 05:44

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20220402_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='display_name',
        ),
        migrations.AddField(
            model_name='sessiondevices',
            name='display_name',
            field=models.CharField(default='hmm', help_text='Name used to identify you in this session, users in this session will be able to see this name.', max_length=50, validators=[users.validators.UsernameValidator()], verbose_name='display name'),
            preserve_default=False,
        ),
    ]
