import Header from './Header';
import Footer from './Footer';
import Head from 'next/head';


const Layout: React.FC<{ 
   title: string, 
   children: React.ReactNode,
   loggedIn: boolean
}> = (props) => {

  return (
      <>
         <Head>
            <title>{props.title + ' | Amicopy'}</title>
            <meta name="description" content="Generated by create next app" />
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
            <link rel="icon" href="/favicon.png" />
         </Head>

         <Header loggedIn={props.loggedIn} />
         <main className="mt-[4.1rem] md:mt-[4.5rem]">{props.children}</main>
         <Footer />
      </>
   )
}

export default Layout
