import Header from './Header'
import Footer from './Footer'
import React from 'react'
import Head from 'next/head';


const Layout: React.FunctionComponent<{ 
   title?: string, children: React.ReactNode 
}> = (props) => {
  const loggedIn = false;

  return (
      <>
         <Head>
            <title>{props.title || "Amicopy"}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
         </Head>

         <Header loggedIn={loggedIn} />
         <main>{props.children}</main>
         <Footer />
      </>
   )
}

export default Layout
