import Header from './Header'
import Footer from './Footer'
import React from 'react'
import Head from 'next/head';


const Layout: React.FunctionComponent<{ 
   title: string, 
   children: React.ReactNode,
   loggedIn: boolean
}> = (props) => {

  return (
      <>
         <Head>
            <title>{props.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
         </Head>

         <Header loggedIn={props.loggedIn} />
         <main className="flex items-center justify-center">
            {props.children}
         </main>
         <Footer />

         <style jsx>{`
            main {
               margin-top: 4.5rem;
            }
            
            /* For xs and sm */
            @media (max-width: 767.99px) {
               main {
                  margin-top: 4.1rem;
               }
            }

         `}</style>
      </>
   )
}

export default Layout
