# Generated by Django 3.2.12 on 2022-03-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sessiondevices',
            name='is_still_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sessiondevices',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='session_devices', related_query_name='session_device', to='transactions.session'),
        ),
    ]
