# Generated by Django 3.2.12 on 2022-03-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20220313_2047'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='text_and_file_not_both_empty',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='shared_on',
            new_name='created_on',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_content', ''), ('files_archive', '')), _negated=True), name='text_and_file_not_both_empty'),
        ),
    ]
