# Generated by Django 3.2.12 on 2022-03-19 04:33

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_device_browser_session_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='browser_session_id_and_user_id_not_both_unset',
        ),
        migrations.RemoveField(
            model_name='device',
            name='browser_session_id',
        ),
        migrations.AddField(
            model_name='device',
            name='browser_session_key',
            field=models.CharField(default='k', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=core.fields.ReadableShortUUIDField(alphabet=None, length=10, max_length=20, prefix='', verbose_name='session code'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('browser_session_key', ''), _negated=True), ('user__isnull', True)), name='browser_session_key_and_user_id_not_both_unset'),
        ),
    ]
