# Generated by Django 3.2.12 on 2022-03-31 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_num_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='num_transactions',
        ),
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='num_transactions',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='browser_session_key',
            field=models.CharField(editable=False, max_length=60, unique=True),
        ),
    ]
