# Generated by Django 3.2.12 on 2022-03-27 12:11

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.fields.ProperEmailField(help_text="We will send a verification code to this email. \n You won't be able to change your email.", max_length=50, unique=True, verbose_name='email address'),
        ),
    ]
