# Generated by Django 3.2.12 on 2022-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_ongoing_sessions',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='num_sessions_assisted',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='num_sessions_created',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='num_transactions_sent',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
