# Generated by Django 3.2.12 on 2022-05-28 07:16

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220329_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Your username should be between 3 and 36 characters and may contain only letters, numbers, hyphens, and underscores; no other characters are allowed.', max_length=36, unique=True, validators=[users.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
